#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-matplotlib
Version  : 3.7.3
Release  : 118
URL      : https://files.pythonhosted.org/packages/bc/06/9ec4ae7c6c3a6e00f19b91439c2f226a4bb4adb24c84a7f8058a2224d2d0/matplotlib-3.7.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/bc/06/9ec4ae7c6c3a6e00f19b91439c2f226a4bb4adb24c84a7f8058a2224d2d0/matplotlib-3.7.3.tar.gz
Summary  : Python plotting package
Group    : Development/Tools
License  : BSD-3-Clause CC-BY-4.0 CC0-1.0 HPND MIT OFL-1.0 OFL-1.1 Python-2.0
Requires: pypi-matplotlib-license = %{version}-%{release}
Requires: pypi-matplotlib-python = %{version}-%{release}
Requires: pypi-matplotlib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : cairo-dev
BuildRequires : freetype-dev
BuildRequires : gtk+-dev
BuildRequires : gtk3-dev
BuildRequires : libpng-dev
BuildRequires : pypi(certifi)
BuildRequires : pypi(kiwisolver)
BuildRequires : pypi(numpy)
BuildRequires : pypi(pillow)
BuildRequires : pypi(py)
BuildRequires : pypi(pybind11)
BuildRequires : pypi(pyparsing)
BuildRequires : pypi(python_dateutil)
BuildRequires : pypi(pytz)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(tornado)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
BuildRequires : python3-tcl
BuildRequires : qhull-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![PyPi](https://badge.fury.io/py/matplotlib.svg)](https://badge.fury.io/py/matplotlib)
[![Downloads](https://pepy.tech/badge/matplotlib/month)](https://pepy.tech/project/matplotlib)
[![NUMFocus](https://img.shields.io/badge/powered%20by-NumFOCUS-orange.svg?style=flat&colorA=E1523D&colorB=007D8A)](https://numfocus.org)

%package license
Summary: license components for the pypi-matplotlib package.
Group: Default

%description license
license components for the pypi-matplotlib package.


%package python
Summary: python components for the pypi-matplotlib package.
Group: Default
Requires: pypi-matplotlib-python3 = %{version}-%{release}

%description python
python components for the pypi-matplotlib package.


%package python3
Summary: python3 components for the pypi-matplotlib package.
Group: Default
Requires: python3-core
Provides: pypi(matplotlib)
Requires: cycler
Requires: pypi(contourpy)
Requires: pypi(fonttools)
Requires: pypi(kiwisolver)
Requires: pypi(numpy)
Requires: pypi(pillow)
Requires: pypi(pyparsing)
Requires: pypi(python_dateutil)

%description python3
python3 components for the pypi-matplotlib package.


%prep
%setup -q -n matplotlib-3.7.3
cd %{_builddir}/matplotlib-3.7.3
pushd ..
cp -a matplotlib-3.7.3 buildavx2
popd

%build
## build_prepend content
sed -e 's|#system_freetype = False|system_freetype = True|' -e 's|#system_qhull = False|system_qhull = True|' mplsetup.cfg.template > mplsetup.cfg
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694532303
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . pyparsing
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
## build_prepend content
sed -e 's|#system_freetype = False|system_freetype = True|' -e 's|#system_qhull = False|system_qhull = True|' mplsetup.cfg.template > mplsetup.cfg
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pypi-dep-fix.py . pyparsing
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-matplotlib
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE %{buildroot}/usr/share/package-licenses/pypi-matplotlib/3683efd59fb44e798efb22fd086a5b1e3a0aa700 || :
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE_AMSFONTS %{buildroot}/usr/share/package-licenses/pypi-matplotlib/91cf189e02755085234dd321326345846bf2949f || :
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE_BAKOMA %{buildroot}/usr/share/package-licenses/pypi-matplotlib/9fa4f855f33fa4ed73c9e6865d534a4f0f910610 || :
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE_JSXTOOLS_RESIZE_OBSERVER %{buildroot}/usr/share/package-licenses/pypi-matplotlib/920b5b7e7e79918ab41e714c4002f3ad4a8fdcfc || :
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE_QT4_EDITOR %{buildroot}/usr/share/package-licenses/pypi-matplotlib/04bb73e33817fa6c0c1259344f7326b408e12885 || :
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE_SOLARIZED %{buildroot}/usr/share/package-licenses/pypi-matplotlib/81b71443d2a101a27194d8d7e0494a93e557a824 || :
cp %{_builddir}/matplotlib-%{version}/LICENSE/LICENSE_YORICK %{buildroot}/usr/share/package-licenses/pypi-matplotlib/fd0bb2832315e88d7a06dd4f28a73f4eac46d3c6 || :
cp %{_builddir}/matplotlib-%{version}/doc/_static/fa/LICENSE %{buildroot}/usr/share/package-licenses/pypi-matplotlib/38f5fae1676b8f00409b0fb2979799ed35320999 || :
cp %{_builddir}/matplotlib-%{version}/doc/devel/license.rst %{buildroot}/usr/share/package-licenses/pypi-matplotlib/96cdc9c40477ab698d63b8c83fab29e2a8f72527 || :
cp %{_builddir}/matplotlib-%{version}/extern/agg24-svn/src/copying %{buildroot}/usr/share/package-licenses/pypi-matplotlib/467189783f672de8baca8b34e798fa2da64166a5 || :
cp %{_builddir}/matplotlib-%{version}/lib/matplotlib/mpl-data/fonts/ttf/LICENSE_DEJAVU %{buildroot}/usr/share/package-licenses/pypi-matplotlib/23e8fed3e3499427ef5a80cbff0aca0946140493 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
pypi-dep-fix.py %{buildroot} pyparsing
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-matplotlib/04bb73e33817fa6c0c1259344f7326b408e12885
/usr/share/package-licenses/pypi-matplotlib/23e8fed3e3499427ef5a80cbff0aca0946140493
/usr/share/package-licenses/pypi-matplotlib/3683efd59fb44e798efb22fd086a5b1e3a0aa700
/usr/share/package-licenses/pypi-matplotlib/38f5fae1676b8f00409b0fb2979799ed35320999
/usr/share/package-licenses/pypi-matplotlib/467189783f672de8baca8b34e798fa2da64166a5
/usr/share/package-licenses/pypi-matplotlib/81b71443d2a101a27194d8d7e0494a93e557a824
/usr/share/package-licenses/pypi-matplotlib/91cf189e02755085234dd321326345846bf2949f
/usr/share/package-licenses/pypi-matplotlib/920b5b7e7e79918ab41e714c4002f3ad4a8fdcfc
/usr/share/package-licenses/pypi-matplotlib/96cdc9c40477ab698d63b8c83fab29e2a8f72527
/usr/share/package-licenses/pypi-matplotlib/9fa4f855f33fa4ed73c9e6865d534a4f0f910610
/usr/share/package-licenses/pypi-matplotlib/fd0bb2832315e88d7a06dd4f28a73f4eac46d3c6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
